name: json_library_parser
description: A Dart package that analyzes other Dart packages and extracts their public API surface as JSON.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  analyzer: ^8.4.0
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
